services:
  regular:
    image: "uexcel247/regular:1.0"
    container_name: "regular-ms"
    ports:
      - "8080:8080"
    depends_on:
      regularDB:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "regular"
      SPRING_DATASOURCE_URL: "jdbc:mysql://regularDB:3306/regular"
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USERNAME: root
      NUMBER_OF_ROOMS: 5
    extends:
      file: common-config.yaml
      service: network-deploy-service

