spring:
  application:
      name: ${APP_NAME:executive}
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3320/executive}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username:  ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8180/realms/eazybankdev/protocol/openid-connect/certs"

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL:http://localhost:8180/realms/eazybankdev/protocol/openid-connect/auth}
  token-url: ${KEYCLOAK_TOKEN_URL:http://localhost:8180/realms/eazybankdev/protocol/openid-connect/token}
server:
  port: 8090